# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-17 10:28
from __future__ import unicode_literals

import apps.client.models
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('companyName', models.CharField(max_length=255, verbose_name='Company name')),
                ('companyAddress', location_field.models.plain.PlainLocationField(default='41.313918406594375, 69.24613952636719', max_length=255, verbose_name='Company address')),
                ('companyPhone', models.CharField(max_length=13, validators=[apps.client.models.phone_validation], verbose_name='Company phone number')),
                ('companyLogo', models.ImageField(upload_to='logos', verbose_name='Company logo')),
            ],
            options={
                'verbose_name': 'Nestle',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shop', models.CharField(max_length=255, verbose_name='Shop')),
                ('due_date', models.DateTimeField(verbose_name='Due date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('address', location_field.models.plain.PlainLocationField(default='41.313918406594375, 69.24613952636719', max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('productName', models.CharField(max_length=255, verbose_name='Product name')),
                ('productType', models.CharField(choices=[('food', 'Food'), ('tech', 'Technology')], max_length=255, verbose_name='Product type')),
                ('productDefinition', models.TextField(verbose_name='Product definition')),
                ('productCost', models.PositiveIntegerField(verbose_name='Product cost')),
                ('relatedCompany', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='client.Company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
