# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 10:37
from __future__ import unicode_literals

import apps.client.models
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('time_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Time')),
                ('token', models.CharField(blank=True, max_length=64)),
                ('companyName', models.CharField(max_length=255, verbose_name='Company name')),
                ('companyAddress', location_field.models.plain.PlainLocationField(default='41.313918406594375, 69.24613952636719', max_length=255, verbose_name='Company address')),
                ('companyPhone', models.CharField(max_length=13, validators=[apps.client.models.phone_validation], verbose_name='Company phone number')),
                ('companyLogo', models.ImageField(upload_to='logos', verbose_name='Company logo')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'Companies',
                'verbose_name': 'Company',
            },
            bases=('client.time',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('time_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Time')),
                ('productName', models.CharField(max_length=255, verbose_name='Product name')),
                ('productType', models.CharField(max_length=255, verbose_name='Product type')),
                ('productDefinition', models.TextField(verbose_name='Product definition')),
                ('productCost', models.PositiveIntegerField(verbose_name='Product cost')),
                ('relatedCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='client.Company')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
            bases=('client.time',),
        ),
    ]
