# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20170115_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created'], 'verbose_name': 'Company', 'verbose_name_plural': 'Nesle'},
        ),
    ]
