# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170115_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Nestle'},
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('food', 'Food'), ('tech', 'Technology')], max_length=255, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='relatedCompany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='client.Company'),
        ),
    ]
